#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Moduware.Tile.Speaker.Droid.Resource", IsApplication=true)]

namespace Moduware.Tile.Speaker.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PCLStorage.Resource.String.ApplicationName = global::Moduware.Tile.Speaker.Droid.Resource.String.ApplicationName;
			global::PCLStorage.Resource.String.Hello = global::Moduware.Tile.Speaker.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060002
			public const int backgroundcolor = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int bottombarcolor = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int instructiontextcolor = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int titlebackgroundcolor = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int titletextcolor = 2131099649;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int back_button = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int speaker_button_off = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int speaker_button_on = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080000
			public const int back_button = 2131230720;
			
			// aapt resource value: 0x7f080004
			public const int defaultStateText = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int defaultSwitch = 2131230725;
			
			// aapt resource value: 0x7f080002
			public const int instructionText = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int myTitle = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int speaker_button = 2131230723;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Header = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Main = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int knob = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int thumb_active = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int track = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int track_active = 2130903043;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int WindowTitle = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int speakerTheme = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
